# Generated by Django 5.0.6 on 2024-06-24 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('driver_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_plate', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=75, verbose_name='Subject')),
                ('class_involved', models.CharField(max_length=75, verbose_name='Classes Involved')),
                ('no_of_people', models.IntegerField()),
                ('purpose', models.CharField(blank=True, max_length=75, verbose_name='Purpose')),
                ('trip_date', models.DateField()),
                ('destination', models.CharField(max_length=75, verbose_name='Destination')),
                ('departure_time', models.TimeField()),
                ('transport_back', models.BooleanField(default=True)),
                ('approx_time_back', models.TimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ManyToManyField(blank=True, to='book.driver')),
                ('vehicle', models.ManyToManyField(blank=True, to='book.vehicle')),
            ],
        ),
    ]
