# Generated by Django 5.0.6 on 2024-07-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
